export interface Product {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: string
  subcategory?: string
  stock: number
  unit: string
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  image: string
  subcategories?: { id: string; name: string; slug: string }[]
}

export interface ChickBatch {
  id: string
  breed: string
  availableDate: string
  pricePerChick: number
  minimumOrder: number
  availableQuantity: number
  description: string
  image: string
}

// Fallback categories for offline/initial render
export const categories: Category[] = [
  {
    id: "chicken-feeds",
    name: "Chicken Feeds",
    slug: "chicken-feeds",
    description: "Premium quality feeds for healthy and productive poultry",
    image: "/chicken-feed-bags-agricultural.jpg",
    subcategories: [
      { id: "chikun-feeds", name: "Chikun Feeds", slug: "chikun-feeds" },
      { id: "ultima-feeds", name: "Ultima Feeds", slug: "ultima-feeds" },
      { id: "happy-chicken-feeds", name: "Happy Chicken Feeds", slug: "happy-chicken-feeds" },
    ],
  },
  {
    id: "dog-feeds",
    name: "Dog Feed & Accessories",
    slug: "dog-feeds",
    description: "Quality nutrition and accessories for your canine companions",
    image: "/dog-food-and-accessories.jpg",
    subcategories: [
      { id: "dog-nutrition", name: "Dog Nutrition", slug: "dog-nutrition" },
      { id: "dog-accessories", name: "Training & Accessories", slug: "dog-accessories" },
    ],
  },
  {
    id: "drugs-vaccines",
    name: "Drugs & Chicken Vaccines",
    slug: "drugs-vaccines",
    description: "Veterinary drugs and vaccines for healthy livestock",
    image: "/veterinary-medicine-vaccines-poultry.jpg",
    subcategories: [
      { id: "vaccines", name: "Vaccines", slug: "vaccines" },
      { id: "antibiotics", name: "Antibiotics", slug: "antibiotics" },
      { id: "vitamins", name: "Vitamins & Supplements", slug: "vitamins" },
    ],
  },
  {
    id: "fish-feeds",
    name: "Fish Feeds",
    slug: "fish-feeds",
    description: "High-protein floating and sinking fish feeds for optimal aquaculture growth",
    image: "/placeholder.svg?height=400&width=400",
    subcategories: [
      { id: "blue-crown", name: "Blue Crown", slug: "blue-crown" },
      { id: "eco-float", name: "Eco Float", slug: "eco-float" },
    ],
  },
]

// Fallback products for offline/initial render
export const products: Product[] = [
  {
    id: "chikun-starter",
    name: "Chikun Starter Mash",
    description: "Premium starter feed for day-old chicks to 4 weeks. High protein formula for optimal growth.",
    price: 12500,
    image: "/chicken-starter-feed-bag.jpg",
    category: "chicken-feeds",
    subcategory: "chikun-feeds",
    stock: 45,
    unit: "25kg bag",
  },
  {
    id: "chikun-super-starter",
    name: "Chikun Super Starter",
    description: "Extra-premium starter feed with enhanced probiotics for the first 2 weeks of life.",
    price: 13800,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "chikun-feeds",
    stock: 30,
    unit: "25kg bag",
  },
  {
    id: "chikun-grower",
    name: "Chikun Grower Mash",
    description: "Balanced nutrition for pullets and broilers from 5 weeks until maturity.",
    price: 11800,
    image: "/chicken-grower-feed-pellets.jpg",
    category: "chicken-feeds",
    subcategory: "chikun-feeds",
    stock: 40,
    unit: "25kg bag",
  },
  {
    id: "chikun-finisher",
    name: "Chikun Broiler Finisher",
    description: "High-energy finishing diet for maximum weight gain in broilers.",
    price: 12200,
    image: "/broiler-finisher-feed.jpg",
    category: "chicken-feeds",
    subcategory: "chikun-feeds",
    stock: 25,
    unit: "25kg bag",
  },
  {
    id: "chikun-layer",
    name: "Chikun Layer Mash",
    description: "Optimized calcium and phosphorus levels for consistent high-quality egg production.",
    price: 13200,
    image: "/layer-feed-for-chickens.jpg",
    category: "chicken-feeds",
    subcategory: "chikun-feeds",
    stock: 50,
    unit: "25kg bag",
  },
  {
    id: "ultima-starter",
    name: "Ultima Premium Starter",
    description: "Ultra-premium starter feed with added vitamins and minerals for rapid early growth.",
    price: 14500,
    image: "/premium-poultry-feed-bag.jpg",
    category: "chicken-feeds",
    subcategory: "ultima-feeds",
    stock: 25,
    unit: "25kg bag",
  },
  {
    id: "ultima-super-starter",
    name: "Ultima Super Starter",
    description: "Advanced formula for the most critical first 10 days of a chick's life.",
    price: 15500,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "ultima-feeds",
    stock: 20,
    unit: "25kg bag",
  },
  {
    id: "ultima-finisher",
    name: "Ultima Broiler Finisher",
    description: "High-energy feed for broilers to achieve maximum market weight efficiently.",
    price: 15000,
    image: "/broiler-finisher-feed.jpg",
    category: "chicken-feeds",
    subcategory: "ultima-feeds",
    stock: 15,
    unit: "25kg bag",
  },
  {
    id: "ultima-plus-special",
    name: "Ultima Plus Special",
    description: "Specially fortified feed with extra nutrients for stressed or high-producing flocks.",
    price: 16000,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "ultima-feeds",
    stock: 10,
    unit: "25kg bag",
  },
  // Happy Chicken Feeds
  {
    id: "happy-pre-starter-elite",
    name: "Happy Chicken Pre Starter Elite+",
    description: "Ultra-premium pre-starter for the most critical early growth phase.",
    price: 14200,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 25,
    unit: "25kg bag",
  },
  {
    id: "happy-pre-starter-commercial",
    name: "Happy Chicken Pre Starter Commercial",
    description: "Standard pre-starter for commercial poultry production.",
    price: 13500,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 30,
    unit: "25kg bag",
  },
  {
    id: "happy-starter-elite",
    name: "Happy Chicken Starter Elite+",
    description: "Premium starter feed for optimized chicken development.",
    price: 13800,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 40,
    unit: "25kg bag",
  },
  {
    id: "happy-starter-commercial",
    name: "Happy Chicken Starter Commercial",
    description: "Quality starter feed for commercial flocks.",
    price: 13000,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 50,
    unit: "25kg bag",
  },
  {
    id: "happy-turkey-starter",
    name: "Happy Turkey Starter",
    description: "Specially formulated high-protein starter for turkey poults.",
    price: 15500,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 15,
    unit: "25kg bag",
  },
  {
    id: "happy-finisher-elite",
    name: "Happy Chicken Finisher Elite+",
    description: "Premium finisher for maximum meat quality and weight.",
    price: 12800,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 35,
    unit: "25kg bag",
  },
  {
    id: "happy-finisher-commercial",
    name: "Happy Chicken Finisher Commercial",
    description: "Efficient finishing feed for commercial broilers.",
    price: 12000,
    image: "/placeholder.svg?height=400&width=400",
    category: "chicken-feeds",
    subcategory: "happy-chicken-feeds",
    stock: 45,
    unit: "25kg bag",
  },
  // Fish Feeds - Blue Crown
  {
    id: "blue-crown-2mm",
    name: "Blue Crown 2mm",
    description: "Floating fish feed, 2mm size for fingerlings.",
    price: 18500,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "blue-crown",
    stock: 20,
    unit: "15kg bag",
  },
  {
    id: "blue-crown-3mm",
    name: "Blue Crown 3mm",
    description: "Floating fish feed, 3mm size for juveniles.",
    price: 18000,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "blue-crown",
    stock: 25,
    unit: "15kg bag",
  },
  {
    id: "blue-crown-4mm",
    name: "Blue Crown 4mm",
    description: "Floating fish feed, 4mm size for post-juveniles.",
    price: 17500,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "blue-crown",
    stock: 30,
    unit: "15kg bag",
  },
  {
    id: "blue-crown-6mm",
    name: "Blue Crown 6mm",
    description: "Floating fish feed, 6mm size for table-sized fish.",
    price: 17000,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "blue-crown",
    stock: 35,
    unit: "15kg bag",
  },
  {
    id: "blue-crown-9mm",
    name: "Blue Crown 9mm",
    description: "Floating fish feed, 9mm size for large fish.",
    price: 16500,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "blue-crown",
    stock: 20,
    unit: "15kg bag",
  },
  // Fish Feeds - Eco Float
  {
    id: "eco-float-3mm",
    name: "Eco Float 3mm",
    description: "Economical floating fish feed, 3mm size.",
    price: 15500,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "eco-float",
    stock: 40,
    unit: "15kg bag",
  },
  {
    id: "eco-float-4mm",
    name: "Eco Float 4mm",
    description: "Economical floating fish feed, 4mm size.",
    price: 15000,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "eco-float",
    stock: 35,
    unit: "15kg bag",
  },
  {
    id: "eco-float-6mm",
    name: "Eco Float 6mm",
    description: "Economical floating fish feed, 6mm size.",
    price: 14500,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "eco-float",
    stock: 30,
    unit: "15kg bag",
  },
  {
    id: "eco-float-9mm",
    name: "Eco Float 9mm",
    description: "Economical floating fish feed, 9mm size.",
    price: 14000,
    image: "/placeholder.svg?height=400&width=400",
    category: "fish-feeds",
    subcategory: "eco-float",
    stock: 25,
    unit: "15kg bag",
  },
  // Dog Feed & Accessories
  {
    id: "dog-premium-adult",
    name: "Premium Adult Dog Food",
    description: "Complete nutrition for adult dogs of all breeds. High in protein and essential vitamins.",
    price: 18500,
    image: "/premium-dog-food-bag.png",
    category: "dog-feeds",
    subcategory: "dog-nutrition",
    stock: 20,
    unit: "15kg bag",
  },
  {
    id: "dog-premium-puppy",
    name: "Puppy Growth Formula",
    description: "Specially formulated for growing puppies to support bone development and immune health.",
    price: 15500,
    image: "/puppy-food-bag.png",
    category: "dog-feeds",
    subcategory: "dog-nutrition",
    stock: 15,
    unit: "10kg bag",
  },
  {
    id: "dog-cane-performance",
    name: "Canine Performance Feed",
    description: "High-protein, high-fat formula for active and working dogs.",
    price: 21000,
    image: "/placeholder.svg?height=400&width=400",
    category: "dog-feeds",
    subcategory: "dog-nutrition",
    stock: 12,
    unit: "15kg bag",
  },
  {
    id: "access-dog-chain",
    name: "Heavy-Duty Dog Chain",
    description: "Durable rust-resistant steel chain for large dogs. 5 feet length with reinforced clasp.",
    price: 4500,
    image: "/placeholder.svg?height=400&width=400",
    category: "dog-feeds",
    subcategory: "dog-accessories",
    stock: 25,
    unit: "piece",
  },
  {
    id: "access-dog-collar",
    name: "Adjustable Nylon Collar",
    description: "Comfortable and durable nylon collar with quick-release buckle. Fully adjustable.",
    price: 1500,
    image: "/adjustable-dog-collar.jpg",
    category: "dog-feeds",
    subcategory: "dog-accessories",
    stock: 40,
    unit: "piece",
  },
  {
    id: "access-dog-leash",
    name: "Reflective Training Leash",
    description: "High-visibility reflective leash for safe walking and training. Padded handle for comfort.",
    price: 3200,
    image: "/dog-leash-heavy-duty.jpg",
    category: "dog-feeds",
    subcategory: "dog-accessories",
    stock: 30,
    unit: "piece",
  },
  {
    id: "access-dog-bowl",
    name: "Stainless Steel Bowl",
    description: "Rust-proof stainless steel feeding bowl with anti-skid rubber base.",
    price: 2800,
    image: "/stainless-steel-dog-bowl.jpg",
    category: "dog-feeds",
    subcategory: "dog-accessories",
    stock: 50,
    unit: "piece",
  },
  // Drugs & Chicken Vaccines
  {
    id: "vaccine-newcastle-lasota",
    name: "Newcastle Disease Vaccine (LaSota)",
    description: "Live virus vaccine for the prevention of Newcastle disease in poultry.",
    price: 3500,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "vaccines",
    stock: 100,
    unit: "200 doses",
  },
  {
    id: "vaccine-gumboro",
    name: "Gumboro Disease Vaccine (IBD)",
    description: "Effective prevention against Infectious Bursal Disease in young chicks.",
    price: 4200,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "vaccines",
    stock: 80,
    unit: "500 doses",
  },
  {
    id: "drug-amino-flash",
    name: "Amino Flash Oral Solution",
    description: "Multi-vitamin and amino acid supplement for stress and growth promotion.",
    price: 7500,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "vitamins",
    stock: 45,
    unit: "1 liter",
  },
  {
    id: "drug-vitalyte",
    name: "Vitalyte (Soluble Powder)",
    description: "Concentrated vitamins, electrolytes, and minerals for rehydration and recovery.",
    price: 1800,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "vitamins",
    stock: 150,
    unit: "100g sachet",
  },
  {
    id: "drug-tylosin",
    name: "Tylosin Tartrate (Soluble)",
    description: "Broad-spectrum antibiotic for the treatment of Chronic Respiratory Disease (CRD).",
    price: 9500,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "antibiotics",
    stock: 25,
    unit: "100g",
  },
  {
    id: "drug-oxytet-soluble",
    name: "Oxytetracycline HCl (Soluble)",
    description: "Generic antibiotic for various bacterial infections in poultry.",
    price: 3200,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "antibiotics",
    stock: 60,
    unit: "100g",
  },
  {
    id: "drug-piperazine",
    name: "Piperazine (Dewormer)",
    description: "Effective deworming solution for roundworms in chickens.",
    price: 1500,
    image: "/placeholder.svg?height=400&width=400",
    category: "drugs-vaccines",
    subcategory: "antibiotics",
    stock: 40,
    unit: "50g sachet",
  },
]

export const dayOldChicksBatches: ChickBatch[] = [
  {
    id: "batch-broiler-jan",
    breed: "Broiler",
    availableDate: "2026-02-01",
    pricePerChick: 850,
    minimumOrder: 50,
    availableQuantity: 2000,
    description: "Fast-growing Cobb 500 broiler chicks",
    image: "/broiler.png",
  },
  {
    id: "batch-layer-jan",
    breed: "Layer (Point of Lay)",
    availableDate: "2026-02-05",
    pricePerChick: 1200,
    minimumOrder: 50,
    availableQuantity: 1500,
    description: "Isa Brown layers - excellent egg producers",
    image: "/layer.png",
  },
  {
    id: "batch-cockerel-jan",
    breed: "Cockerel",
    availableDate: "2026-02-10",
    pricePerChick: 450,
    minimumOrder: 100,
    availableQuantity: 3000,
    description: "Hardy local cockerels for meat production",
    image: "/cockerel.png",
  },
  {
    id: "batch-noiler-jan",
    breed: "Noiler",
    availableDate: "2026-02-15",
    pricePerChick: 650,
    minimumOrder: 50,
    availableQuantity: 1000,
    description: "Dual-purpose Noiler birds - meat and eggs",
    image: "/noiler.png",
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    minimumFractionDigits: 0,
  }).format(price)
}
